#!/usr/bin/env sh

function yabai_rule {
  yabai -m rule --add "$@"
  yabai -m rule --apply "$@"
}

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

for idx in $(yabai -m query --spaces | jq '.[].index | select(. > 1)' | sort -nr); do
  yabai -m space --destroy "$idx"
done

# Restore default application layering
yabai_rule app=".*" layer=normal

# Default layout (bsp, stack, or float)
yabai -m config layout bsp

# Disable screen switching animation
yabai -m config window_animation_duration      0.0

# Spaces setup
yabai -m space 1 --label terminal
yabai -m space web --display 1

yabai -m space --create
yabai -m space 2 --label media

yabai -m space --create
yabai -m space 3 --label social

yabai -m space --create
yabai -m space 4 --label tasks

yabai -m space --create
yabai -m space 5 --label notes

yabai -m space --create
yabai -m space 6 --label email

yabai -m space --create
yabai -m space 7 --label design

yabai -m space --create
yabai -m space 8 --label dev

yabai -m space --create
yabai -m space 9 --label misc

yabai -m space 10 --label web

yabai -m space design --display 2
yabai -m space dev --display 2
yabai -m space misc --display 2

yabai -m space social --layout stack
yabai -m space tasks --layout stack
yabai -m space notes --layout stack
yabai -m space email --layout stack
yabai -m space design --layout stack
yabai -m space dev --layout stack

# Assign apps to space
yabai_rule app="^Safari|Arc$" space=web
yabai_rule app="^WezTerm$" space=terminal
yabai_rule app="^Beeper|Discord|Messages$" space=social
yabai_rule app="^Notes$" space=notes
yabai_rule app="^Things$" space=tasks
yabai_rule app="^Spark$" space=email
yabai_rule app="^Figma$" space=design
yabai_rule app="^Polypane$" space=dev
yabai_rule app="^Spotify$" space=media

# Padding
yabai -m config top_padding 24
yabai -m config right_padding 24
yabai -m config bottom_padding 24
yabai -m config left_padding 24
yabai -m config window_gap 12

# Mouse mode
yabai -m config mouse_follows_focus off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move # modifier + left-click drag to move window
yabai -m config mouse_action2 resize # modifier + right-click drag to resize window
yabai -m mouse_drop_action swap # swap window when dropped on center, split when dropped on edge

# Ignore apps
yabai_rule app="^System Settings$" manage=off
yabai_rule app="^Finder$" manage=off
yabai_rule app="^Preview$" manage=off
yabai_rule app="^Cleanshot X$" manage=off
yabai_rule app="^1Password$" manage=off grid=6:4:1:1:2:4
yabai_rule app="^Raycast$" manage=off
yabai_rule app="^kindaVim$" manage=off
yabai_rule app="^Wooshy$" manage=off
yabai_rule app="^Herd$" manage=off
yabai_rule app="^Clop$" manage=off
yabai_rule app="^UTM$" manage=off

yabai_rule app="^Arc$" title="^$" mouse_follows_focus=off # arc pip
yabai_rule label="Little Arc" app="^Arc$" title="^Space.*" manage=off # arc little arc

yabai -m signal --add event=window_created \
    app=Arc \
    action="osascript -e 'display dialog \"New window created in Arc\" & name of front window'"
