#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

for idx in $(yabai -m query --spaces | jq '.[].index | select(. > 1)' | sort -nr); do
  yabai -m space --destroy "$idx"
done

# Restore default application layering
yabai -m rule --add app=".*" layer=normal

# Default layout (bsp, stack, or float)
yabai -m config layout bsp

# Disable screen switching animation
yabai -m config window_animation_duration      0.0

function setup_space {
  local idx="$1"
  local name="$2"
  local layout="${3:-bsp}"
  local display="${4:-1}"
  local space=
  echo "setup space $idx : $name on display $display"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name" --layout "$layout" --display "$display"
}

# Spaces setup
yabai -m space 1 --label terminal
yabai -m space web --display 1

yabai -m space --create
yabai -m space 2 --label media

yabai -m space --create
yabai -m space 3 --label social

yabai -m space --create
yabai -m space 4 --label tasks

yabai -m space --create
yabai -m space 5 --label notes

yabai -m space --create
yabai -m space 6 --label email

yabai -m space --create
yabai -m space 7 --label design

yabai -m space --create
yabai -m space 8 --label dev

yabai -m space --create
yabai -m space 9 --label misc

yabai -m space 10 --label web

yabai -m space design --display 2
yabai -m space dev --display 2
yabai -m space misc --display 2

yabai -m space social --layout stack
yabai -m space tasks --layout stack
yabai -m space notes --layout stack
yabai -m space email --layout stack
yabai -m space design --layout stack
yabai -m space dev --layout stack

# yabai -m space --create
# yabai -m space 8 --label design
# yabai -m space design --display 2

# yabai -m space web --display 2
# setup_space 1 web
# setup_space 2 terminal
# setup_space 3 social stack
# setup_space 4 notes stack
# setup_space 5 tasks stack
# setup_space 6 email stack
# setup_space 7 design stack
# setup_space 8 media stack
# setup_space 9 foo
# setup_space 10 bar
# setup_space 11 baz

# Assign apps to space
yabai -m rule --add app="^Safari|Arc$" space=web
yabai -m rule --add app="^WezTerm$" space=terminal
yabai -m rule --add app="^Beeper|Discord|Messages$" space=social
yabai -m rule --add app="^Notes$" space=notes
yabai -m rule --add app="^Things$" space=tasks
yabai -m rule --add app="^Spark$" space=email
yabai -m rule --add app="^Figma$" space=design
yabai -m rule --add app="^Polypane$" space=dev
yabai -m rule --add app="^Spotify$" space=media

# Padding
yabai -m config top_padding 24
yabai -m config right_padding 24
yabai -m config bottom_padding 24
yabai -m config left_padding 24
yabai -m config window_gap 12

# Mouse mode
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move # modifier + left-click drag to move window
yabai -m config mouse_action2 resize # modifier + right-click drag to resize window
yabai -m mouse_drop_action swap # swap window when dropped on center, split when dropped on edge

# Ignore apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Cleanshot X$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^kindaVim$" manage=off
yabai -m rule --add app="^Wooshy$" manage=off
yabai -m rule --add app="^Herd$" manage=off
yabai -m rule --add app="^Clop$" manage=off
yabai -m rule --add app="^UTM$" manage=off
